Guest auth frontend for omniport
IMGIITRoorkee/omniport-frontend-auth pull request #1
Opened 2019-12-18 21:18 UTC by rish9101

2019-12-18 21:25 UTC, pradumangoyal commented on src/actions/index.js
> +      console.log(isGuest)
Remove consoles

2019-12-18 21:28 UTC, pradumangoyal requested changes
Please push the required changes at the earliest

2019-12-18 21:28 UTC, pradumangoyal commented on src/actions/index.js
> +  return async dispatch => {
Implement this thing using JS promises

2019-12-18 21:28 UTC, pradumangoyal commented on src/actions/index.js
> +      var isGuest =false;
Use let

2019-12-18 21:28 UTC, pradumangoyal commented on src/actions/index.js
> +      for (var index = 0; index < roles.length; ++index) {
You should use an already written function in the `formula_one` for the same purpose: https://omniport.readthedocs.io/en/latest/references/formula_one/functions/if_role.html#if-role

2019-12-19 04:27 UTC, pradumangoyal commented
This can be merged according to frontend coding practices. @ayushjn20 Review this and merge it with the PR on the backend asap.

2019-12-21 16:24 UTC, liquidslr commented on src/components/login.js
> +    console.log(url)
Remove all the debug statements before pushing the code

2019-12-21 16:32 UTC, liquidslr commented on src/actions/index.js
> +        isGuestAuth: isGuest
can be shortened by using a ternary operator

2019-12-21 16:45 UTC, liquidslr requested changes

2019-12-21 16:45 UTC, liquidslr commented on src/components/login.js
> +    const url = this.state
Use destructuring

2019-12-26 17:59 UTC, pradumangoyal commented
Value of the new prop should be `False` by default so that it doesn't change the expected behaviour of the already present apps.

2019-12-29 05:27 UTC, pradumangoyal approved these changes

2019-12-30 07:54 UTC, liquidslr approved these changes

2020-01-11 11:08 UTC, merged